### ISSUE TITLE
Same item proposed multiple times in item roll

### ISSUE THREAD

**Issue by dratinyy** [pagefaultgames/pokerogue#100]
It happened several times to me that the same item was offered multiple times in the same item roll. Not sure if this is intentional, but it is a poor experience. I believed it happened after the first roll (it should be possible to confirm using the wave number and reroll cost).

![image](https://github.com/pagefaultgames/pokerogue/assets/24292164/cca3c25e-2e94-40ff-b39b-ff647ab41cab)
![image](https://github.com/pagefaultgames/pokerogue/assets/24292164/2d96cfb6-9765-4f67-bfef-56ed873ccf03)

**Comment by Gammer0909** [comment]
I don't believe this should be a problem, no? When you have multiple items available to you, eventually you're going to get repeats, especially when they're all common items.

**Comment by dratinyy** [comment]
I think when you get only 3 items in a roll, rolling the same twice can be frustrating as it narrows your options down from 3 to 2 which is a lot, however it does not seem to appear often so it is not too annoying.

**Comment by Gammer0909** [comment]
@dratinyy Due to the fact that this doesn't happen very often, and that when you did it had a large sample size (more choices) this isn't going to be an issue. As you get more choices and go through the game, the chances of getting a duplicate go up too. It didn't happen that often because the chances are incredibly small, and even when it does it's a minor inconvenience, not a game-breaking issue.

**Comment by bennybroseph** [comment]
with the changes to Luck this should be less of an issue now as higher tier items should appear more often as you play more
