### ISSUE TITLE
I think my male Kirlia wanted to be a Gardevoir

### ISSUE THREAD

**Issue by Thesgtkirby** [pagefaultgames/pokerogue#1101]
Who's to stop him? It looks like it was an intended choice which strikes me as odd. Why would someone add something so specific as gender based evolutions to an evolution that wasn't based on pokemon gender? In every pokemon game since gen 3, a male Kirlia could still evolve into a Gardevoir. Maybe someone finds this very purposely designed mechanic to be annoying for some reason. I feel like a sane and reasonable person shouldn't have an issue with this unless they are petty in nature.

**Comment by NotSalad-in** [comment]
Why are you only focusing on Gardevoir and not also mentioning Gallade being genderlocked to male?

Do you have a thing for Gardevoir?

**Comment by CodeTappert** [comment]
Does Kirlia need an item to evolve to gallade currently (in pokerouge)

If not this might explain why is it set that way.
https://github.com/pagefaultgames/pokerogue/blob/6fa7412465b99d38944c124ec49d52b010d8d5c7/src/data/pokemon-evolutions.ts#L429

**Comment by CodeTappert** [comment]
Okay i looked more at the code. 
I mean we could really implement it the way it is in the games. I dont see a code reason not to do  it....

I will look at it

**Comment by guest1511** [comment]
> Okay i looked more at the code. I mean we could really implement it the way it is in the games. I dont see a code reason not to do it....
> 
> I will look at it

As another player that likes the pokemon. I ask that if that the evolution must change, make it where Gardevoir and Gallade are as controllable as they are now and not with the stone evolution. It being gender locked is an elegant mechanical solution instead of nerfing Gallade behind a stone evolution. Something to note is that the discord server before lockdown did discuss a possible solution being that of having a prompt on evolution for krilia that you could choose whether to have it evolve into Gallade/Gardevoir regardless of gender.

**Comment by Xavion3** [comment]
To summarise why this was done, this and snorunt were changed into split gender evolutions as a buff to these pokemons usability as starters. Kirlia and snorunt are not great pokemon, both really want to evolve to be capable. With the mechanic in the games in addition to the gender you also need to find a dawn stone which meant if you wanted a froslass or gallade you'd often struggle immensely sometimes having to wait 100+ waves hoping to be able to evolve your pokemon. Evolution stone chances are higher than they're used to be, but it can still feel punishing having to wait so long. Kirlia's stats are *really* bad after all. 

This change made them much more usable as starter pokemon, as you could consistently hit your preferred form by just choosing a particular gender at the starter selection screen.

While this can be potentially changed, and we are open to changing it, it is worth being aware this is indirectly nerfing both gallade and froslass to do this so it's being considered carefully.

**Comment by CodeTappert** [comment]
I agree with @Xavion3 
To change the code is quite easy. (to make it like the games for example).

But this will nerve the formes that require a stone. 

If there ever is a decision made by the team i am happy to impelment it

**Comment by AngelOShadows** [comment]
I don't have them currently, as I can't dedicate my time to trying out every single pokemon that evolves via stone -- but if the change was made to make Kirlia and Snorunt more viable as starters, what about pokemon like Jigglypuff, Shellder, Voltorb, Sunkern, Skitty, the entire Pan trio, Minccino, Charcadet, and Eevee? They all have similar -- some have worse -- stats to Kirlia & Snorunt.

**Comment by KassandraOst** [comment]
i don't think this would affect ralts as a starter as it's not too difficult to get both genders anyhow, it'd be more in catching wild ralts, but I think it should be at least changed to vanilla game where gardevoir is male and female as that's what's expected by the evolution

**Comment by Thesgtkirby** [comment]
> To summarise why this was done, this and snorunt were changed into split gender evolutions as a buff to these pokemons usability as starters. Kirlia and snorunt are not great pokemon, both really want to evolve to be capable. With the mechanic in the games in addition to the gender you also need to find a dawn stone which meant if you wanted a froslass or gallade you'd often struggle immensely sometimes having to wait 100+ waves hoping to be able to evolve your pokemon. Evolution stone chances are higher than they're used to be, but it can still feel punishing having to wait so long. Kirlia's stats are _really_ bad after all.
> 
> This change made them much more usable as starter pokemon, as you could consistently hit your preferred form by just choosing a particular gender at the starter selection screen.
> 
> While this can be potentially changed, and we are open to changing it, it is worth being aware this is indirectly nerfing both gallade and froslass to do this so it's being considered carefully.

I don't think this is the best way to go about this. To buff both Kirlia and Snorunt you could have a prompt to access either evolution so you don't get confused. Or have an early game item that you can get cheap (or free) that allows you to pick the gender or evolution would be way better than this strange confusing mess that's currently used.

**Comment by guest1511** [comment]
> I don't have them currently, as I can't dedicate my time to trying out every single pokemon that evolves via stone -- but if the change was made to make Kirlia and Snorunt more viable as starters, what about pokemon like Jigglypuff, Shellder, Voltorb, Sunkern, Skitty, the entire Pan trio, Minccino, Charcadet, and Eevee? They all have similar -- some have worse -- stats to Kirlia & Snorunt.

For Krilia, having a good gallade moveset, like using its Gallade-focused egg moves, makes it a really bad Krilia because it has terrible attack while the special attack is serviceable at level 20. The others start the evolution stone hunt at level 1, don't have this anti-synergy going on, where even if waiting for the stone in the 100+ wave mark, you can still say you have a decent pre-evolution of that pokemon or have better mid-game forms. To put Gallade behind a stone evolution while stuck with a physical Krilia is to make it a worse Meltan but not even evolve into Melmetal for your troubles. Tyrogue can be annoying to get into a Hitmontop primarily for early game players if they don't have equal attack/defense IVs but if both are maxed or equal, than its a simple choice of nature, you're probably likely to have most unlocked by the time you have it with best IVs and thus it becomes a choice at the starter screen. Though this is in comparison to the vanilla stone evolution, if wanting to have our cake and eat it too, the best solution for Snorunt and Krilia would be to make it a prompt on evolution, allowing male gardevoirs/frosslasses and female gallades, instead of unnecessarily nerfing frosslas/gallade by tagging them to stone evolution.

**Comment by RedRobot0** [comment]
I think the reversion is entirely unnecessary, it literally doesn't matter what gender it is. It's just a way to make the game design better because why is gallade gender locked but not Gardevoir, why aren't you complaining your female kirlia can't turn into gallade? it's literally a fictional character in a fangame website it's really not that deep

**Comment by Thesgtkirby** [comment]
> I think the reversion is entirely unnecessary, it literally doesn't matter what gender it is. It's just a way to make the game design better because why is gallade gender locked but not Gardevoir, why aren't you complaining your female kirlia can't turn into gallade? it's literally a fictional character in a fangame website it's really not that deep

Never once did I say I didn't want that either. I wish both were the case because getting a good gallade stat female ralts and a good Gardevoir stat male ralts is annoying without the option to pick. My issue is that there's now even less options than before. I find it slightly pathetic that you'd jump to some crazy conclusion like that. I think you just want to stroke the fire without adding anything to the conversation

**Comment by RedRobot0** [comment]
why are we saying "wanted" like you're talking to these Pokémon? this is literally... a fangame... they cant WANT ANYTHING 😭

**Comment by Thesgtkirby** [comment]
> why are we saying "wanted" like you're talking to these Pokémon? this is literally... a fangame... they cant WANT ANYTHING 😭

First of all; zero imagination. Second of all: I only stated the title as such because I believe a lot of these changes they made feel more like weird projections than purposeful changes for balance. If a male ralts has better sp atk stats than phys atk then I think it can still be a Gardevoir. If a female ralts has a good nature for sp atk but bad phys atk, then I want it to be a Gallade. The silly title was more to grab attention than state anything concrete

**Comment by guest1511** [comment]
>Never once did I say I didn't want that either. I wish both were the case because getting a good gallade stat female ralts and a good Gardevoir stat male ralts is annoying without the option to pick

Not in defense in the tact of RedRobot but your original post, and the two people that tried to make alterations, only made reference/alterations for male gardevoir, not of female gallade. It is a bad faith interpretation just as it is bad faith to imagine the current evolution change was of nothing more than good streamlining of gameplay. The idea of female gallade wasn't once uttered in your OP (_a way to have fixed this is to phrase it as a general krilia change instead of specifically a gardevoir change_) and was first mentioned by other people.

>My issue is that there's now even less options than before. I find it slightly pathetic that you'd jump to some crazy conclusion like that. I think you just want to stroke the fire without adding anything to the conversation

Odd instance of technically less options but functionally more because of player control. Reverting to vanilla stone evolution lets three outcomes exist, male/female gardevoir and male gallade but at the cost of player control/agency, making Gallade a much harder evolution to make work. If I'm planning a team out, while I do have the option of male Gardevoir, it comes at the functional cost of gallade entirely since it's a gamble and the worst case scenario is that I'm stuck with an awful krilia who's only purpose is to be a switch in for dragon types, not even having a good speed stat for utility like paralysis, sleep, or doing stat modifiers. It is a roguelike so rng is a part of it but it can also be controlled and there is such a thing as too much or unhealthy rng. Of course in the instance of just allowing the evolution to be a prompt on hitting level 30 allowing both male gardevoirs and female gallade, this is solved with the only hiccup being an extra menu prompt being made on evolution which might inconvenience someone but I'd assume this is an extremely minor inconvenience compared to being cursed to evo-stone rng. Also this can apply for Snorunt in relation to Frosslass and Glaile, a prompt in evolution instead of an evolution stone for the sake of preserving player agency.

**Comment by Fontbane** [comment]
I think I have a solution to this that would stay close to mainline without nerfing Kirlia, while also fixing the issue of regional evolutions. The player could have a way to switch a mon's "track", determining what it would evolve into.

One way of doing this would be an item for track switching. For example, if you use a Strange Souvenir on Pikachu, its track will be switched to Alolan Raichu, and it will evolve into Alolan Form if you use a Thunder Stone later. The Dawn Stone could be implemented as a track switching item rather than an evolution item. Track switching items could be easier to find than evolution items.

Alternatively, we could have the player set the track in the party menu, similar to the current functionality for locking evolutions after you cancel one. I think this would be the best way. For regional forms, we could require the player to unlock track switching by catching the regional form. We could also have items, like the Dawn Stone, that switch the tracks, and then permanently enable the track switching option for that mon.

The way this would work would be, for example:
- You have a male Kirlia either as a starter or a wild capture. Its evolution track is set by default to evolve into Gardevoir.
- You come across a Dawn Stone through an item roll, let's say it has a weight of 10 and is Great tier. Using it on Kirlia switches its track to Gallade.
- In the party menu, similar to locking/unlocking a mon from evolving, there's an option to switch the track back and forth from Gallade to Gardevoir. If you've caught or used a Gallade before, this option will be present for any future Kirlia in future runs.
- When you meet the evolution requirement of the mon your track is set to, it undergoes the appropriate evolution.

There could be different requirements to permanently unlock track switching. For example, it might be appropriate if you could only find a track switching item for regional forms in specific biomes, such as Island for Strange Souvenir. Or, the player could unlock track switching for regional forms by entering the biome with that mon or having caught the evolution before. 

There are several ways this could be done, but tl;dr the evolution locking mechanic can be leveraged to give the player choice over their evolution. If we do this, male Kirlia could still evolve into Gallade at level 30, provided its evolution track has been set to Gallade.

**Comment by guest1511** [comment]
>Without nerfing Krilia
_Still demands an item to be rolled in the shop_, the way to do it without nerfing Krilia is to not have the shop or item rolls involved at all, if you do that, you've nerfed Krilia and Gallade by extension, especially if the first way a player may be enticed into trying gallade is by getting one of its egg moves and thus the first time they worry about Gallade, it's behind rng. Will also note that Gallade isn't the easiest find in the wild, only existing as a rare boss in Dojo or super rare as a normal encounter. Admittedly the nerf you're applying is a lighter one than just having gallade as a forever stone evolution as, from my understanding, after you get the first gallade its not rng dependent though it'd add having to go back into the party menu whenever you catch the pokemon to set its track instead of just going into the next wave knowing what it'll evolve into, or in the case of having the prompt in the evolution menu, just a singular button press in a menu you are going to already meaning there's less menu management needing to happen. You aren't catching a pokemon and then back-tracking into the party menu by selecting a potion to set a mon's track, and then going into the next wave, it's pokemon hits 30 (_krilia as the example_), evolves, you have two-button prompt for gallade/gardevoir, and then evolution cutscene into the next wave, or with how it is now, you see krilia's gender, know what it'll be by level 30 and you have no extra menus to be running through allowing for a more seamless run.

**Comment by CandleClockwork** [comment]
I'm sorry, but wouldn't the simplest solution to have Kirlia and Snorunt evolve into Gallade/Glalie by dawn/daytime and Gardevoir/Froslass by dusk/nighttime at their respective levels? This would allow both forms to be evenly available, makes relative sense, and solves the whole gender conundrum by allowing you to have both a male Gardevoir and/or a female Gallade.

**Comment by guest1511** [comment]
A thing to note with the proposed time-based evolution change, and this is more for pokerogue in general, a more direct indicator of the time of day during runs would be appreciated to help the player gauge the evolution paths for the hisuian forms or weavile and the spawns for some biomes like Meadows.

**Comment by Adri1** [comment]
Idk what it's worth, but I would simply propose that we keep the initial mechanic with Gardevoir/Glalie by level up, and Gallade/Froslass by a Dawn Stone, but for BOTH genders.

**Comment by Rosalie-A** [comment]
> To summarise why this was done, this and snorunt were changed into split gender evolutions as a buff to these pokemons usability as starters.

alright, I'm going to say it.

There needs to be some proof of this given the departed dev's views and how further restricting pokemon gender comes across in that light (because let's face it, if the deviation from vanilla was simply allowing female Gallade instead this likely wouldn't be as much of a topic), especially as how the discussion has focused primarily on the Ralts line (known as a trans icon to many) and not the Snorunt line (known as an ice pokemon). If there were conversations confirming this change was made for gameplay convenience, great. I'll still have the change in my personal fork but that's the beauty of open source. If there's no evidednce of that though, then gender restricting evolutions in a way divergent from vanilla going forward is not a great look, regardless of the new team's intentions.

**Comment by Maplelily** [comment]
Honestly, I think the system as it is now is the most convenient as it lets you very easily predetermine which Evolution you'll get, allowing you to easily focus your moveset around suiting that choice. Instead of relying on MAYBE pulling a Dawn Stone.
That aside, I'm going to very heavily advocate against the Male Froslass suggestions at the very least with how heavily it goes against its dex entries and the folklore of the Yuki-onna, that Froslass is based on. I'm not going to throw my hat into the ring regarding Gallade since I don't think that there's any lore supporting it. But at the very least, Froslass should remain exclusively female, I feel.

**Comment by Cycrum** [comment]
> > To summarise why this was done, this and snorunt were changed into split gender evolutions as a buff to these pokemons usability as starters.
> 
> alright, I'm going to say it.
> 
> There needs to be some proof of this given the departed dev's views and how further restricting pokemon gender comes across in that light (because let's face it, if the deviation from vanilla was simply allowing female Gallade instead this likely wouldn't be as much of a topic), especially as how the discussion has focused primarily on the Ralts line (known as a trans icon to many) and not the Snorunt line (known as an ice pokemon). If there were conversations confirming this change was made for gameplay convenience, great. I'll still have the change in my personal fork but that's the beauty of open source. If there's no evidednce of that though, then gender restricting evolutions in a way divergent from vanilla going forward is not a great look, regardless of the new team's intentions.

It's especially questionable, given that Meloetta was deliberately changed to be female in PokeRogue, and Diancie was originally changed that way before being reverted to gender unknown like in the main series.

**Comment by karl-police** [comment]
> I agree with @Xavion3 To change the code is quite easy. (to make it like the games for example).
> 
> But this will nerve the formes that require a stone.
> 
> If there ever is a decision made by the team i am happy to impelment it

If the code base would have more comments, for sure would be more easy

**Comment by Cycrum** [comment]
I personally wouldn't close it until male Gardevoir is at least obtainable in-game. Ideally, Meloetta should also be made genderless.

**Comment by Tempo-anon** [comment]
Male Gardevoir is obtainable in-game now so I will close this issue out.
