### ISSUE TITLE
Don't let Pickup select items that are capped

### ISSUE THREAD

**Issue by OnmiKhaos** [pagefaultgames/pokerogue#1198]
A suggestion that pickup skip over items such as berries if the mon with Pickup already has a full stack. It helps create strategy in late-game endless runs by strategically filling out a Pickup mon, making it easier to get lucky eggs and boosting items.

**Comment by pedwards95** [comment]
Possibly can apply to Grip Claw as well.

**Comment by JoannaFalkowska** [comment]
I don't think that's a balanced idea tbh. This would make Magician unfathomably broken even beyond how broken it already is. With Multi-Lens you'd not only get _some_ type-boosting items from bosses, you'd get ALL of them ALL the time.

**Comment by Gaikotsu2** [comment]
Just a thought regarding Grip Claw and Black Hole. Allow them to pick items that you are already capped on, but remove the picked item from the enemy then discard it (and provide a message saying it did so). 

This would make it feel better to use since you would see it doing something each time it proc'd.

**Comment by innerthunder** [comment]
This was decided against by the balance team. Pickup and other item-stealing effects are already exceptional boosts to item economy; buffing them any further seems unnecessary.
