### ISSUE TITLE
moves that "increase damage when used repeatedly" do not increase damage properly

### ISSUE THREAD

**Issue by fight3rmn** [pagefaultgames/pokerogue#1298]
The two I've seen this problem with are rollout and echoed voice. The power is supposed to increase by 40 each turn for echoed voice and double each turn for rollout, but it is simply doing similar damage on each consecutive turn it is used. Will test more, but it looks like the damage is slightly increasing but not doing so properly. My guess is that either the number of turns used isn't being tracked properly, or the damage is somehow being reset each turn.

**Comment by zacharied** [comment]
I went and investigated this because those attacks have always felt sort of off to me as well. I have been testing using [a unit test on my fork](https://github.com/zacharied/pokerogue/blob/6edb266953897ce20e170f39d711708e251fb0c1/src/test/moves/consecutive_hit_moves.test.ts). Basically, it simulates the following:
* A player and similarly-leveled opponent with near-infinite HP that only knows Splash
* The player uses Fury Attack/Rollout/whatever 3 times, and we track the HP damage dealt by the attack each time
* We `expect` that the damage roughly doubled each turn it was used
* We run this test 50 times and average the results for each turn

I've compiled the results here.

For Rollout:
```ts
[ 33.372549019607845 ]
[ 64.2156862745098 ]
[ 125.7843137254902 ]
```

For Fury Attack:
```ts
[ 42.35294117647059 ]
[ 82.3529411764706 ]
[ 162.1764705882353 ]
```

So it seems like everything is working... i'll have to investigate more.

**Comment by zacharied** [comment]
Oh, if I had just tested one more turn I would have run into the answer with Fury Cutter: these moves have a max BP that they can be doubled up to. Fury Cutter can be doubled for 3 turns. Echoed Voice can be doubled for 5. [Source](https://pokemondb.net/move/rollout).

@fight3rmn, is it possible you had just already hit the limit of the power stacking for Echoed Voice when you observed the problem?

**Comment by innerthunder** [comment]
Fixed this while implementing interactions with Parental Bond (https://github.com/pagefaultgames/pokerogue/pull/2384).

**Comment by Snailman11** [comment]
Rollout Currently does not force the user into repeating it
