### ISSUE TITLE
Combusken Flame Charge showing debuff Animation instead of Buff Animaton

### ISSUE THREAD

**Issue by Luna-Light** [pagefaultgames/pokerogue#1317]
#### Context:
When Combusken uses the move `Flammenladung` (Flame Charge) in the German version of the game, there is an inconsistency with the animation and the text displayed.

#### Issue:
- Currently, using `Flammenladung` shows the blue debuff animation.
- However, the text correctly indicates "Init stieg" (Speed rose), which means it should show an orange buff animation instead.

#### Resolution:
The move `Flammenladung` needs to show the orange buff animation because it increases the Pokémon's Speed (`Init`). 

#### Additional Information:
- The move `Flammenladung` was obtained by leveling up.

**Comment by geefuoco** [comment]
So I think this is a bit of a weird problem. 

https://github.com/pagefaultgames/pokerogue/assets/87877876/3a33a553-1e98-4854-8798-f3e3d2d209d3

The animation is still playing upwards, but because of texture, it can look like its dropping the stat. 

The `BattleStat[filteredStats[0]].toLowerCase()` in the snippet below prints out 'spd' which refers to the blue texture in `/images/effects/battle_stats.png`
![image](https://github.com/pagefaultgames/pokerogue/assets/87877876/aeee9812-52c5-4803-b413-742b866eb0a1)


In this case, each stat has a specific color. 

And this is the snippet in `phases.ts` where the stat sprite is being set.
```ts
      const statSprite = this.scene.add.tileSprite(tileX, tileY, tileWidth, tileHeight, "battle_stats", filteredStats.length > 1 ? "mix" : BattleStat[filteredStats[0]].toLowerCase());
      statSprite.setPipeline(this.scene.fieldSpritePipeline);
      statSprite.setAlpha(0);
      statSprite.setScale(6);
      statSprite.setOrigin(0.5, 1);
```

So really, a decision would have to be made on what is the best approach for showing stat increase / decrease and if that should change

**Comment by j-diefenbach** [comment]
I think this isn't much of an issue. It's just that combuskens width and offset makes it look like a downwards stroke but the texture still clearly moves upwards. 
> So really, a decision would have to be made on what is the best approach for showing stat increase / decrease and if that should change

Any fix to this would either involve changing the sprites or completely reworking the way the texture is shown which seems unnecessary since there's text anyways.

**Comment by geefuoco** [comment]
I do think from a user experience perspective, it would be better to only use the blue texture for decreases in stat, since it would align with how it worked in the base games.

![d9aieh6-c65d0802-f28e-450e-b279-00631e873ec2](https://github.com/pagefaultgames/pokerogue/assets/87877876/50676ce3-4d96-4e6a-bde1-bf376bfa1394)

**Comment by j-diefenbach** [comment]
Yeah I agree, just a point of enhancement tbh
