### ISSUE TITLE
Question about Beat up condition

### ISSUE THREAD

**Issue by hayuna** [pagefaultgames/pokerogue#1366]
I have a question about this move. Some sources (https://pokemondb.net/move/beat-up) saying that pokemons with status FAINT, FROZEN, PARALYSED, SLEEP will not attend this move

```
Let's say we have the ultimate team of 1 Weavile and 5 Magikarp. One of the Magikarp is paralyzed, so only 4 can attack with Beat Up. [...] Beat Up would attack 5 times [...]
```

Should it be added to the condition of this move? From logic perspective if pokemon is paralysed or frozen, cannot attack

**Comment by Upos1997** [comment]
From what I can see this is already the case no?

**Comment by hayuna** [comment]
Not exaclty, 
<img width="1389" alt="Screenshot 2024-05-25 at 21 22 00" src="https://github.com/pagefaultgames/pokerogue/assets/19636010/d650d029-037f-4c89-8462-42e7dc7e20f7">

In this example Bulbasaur (no status), Spearow (burn) and Ekans (no status) should attack. But we can see that there were only 2 hits

**Comment by td76099** [comment]
Where does it list those status conditions on the site? The only excerpt I see is `Beat Up deals damage from each Pokémon on your team that does not have a status ailment (nor is fainted).` which would include Burn.

[Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Beat_Up_(move)#Generation_II) describes it as any Pokemon with a non-volatile status condition cannot participate. [Non-volatile status info here](https://bulbapedia.bulbagarden.net/wiki/Status_condition#Non-volatile_status). The code already does that. That's why it checks if the Pokemon has a status effect
