### ISSUE TITLE
Pokémon selection screen bug when pressing ENTER and SPACE simultaneously

### ISSUE THREAD

**Issue by SnowCharmQ** [pagefaultgames/pokerogue#1392]
In the SelectStarterPhase, if I have already selected one/two Pokémon(s) and press the ENTER key to start the game, while also quickly pressing the SPACE key, the following situation occurs. 
![R738J${YD8UZ{8NJGY7DY%8](https://github.com/pagefaultgames/pokerogue/assets/82224175/c8e63c70-d6ea-4f5a-9223-487032da482c)
At this point, I can still enter the game, but the Pokémon selection options remain displayed on the screen and cannot be removed.
![VVTXQW)OMGX(OOMNBDK33ZP](https://github.com/pagefaultgames/pokerogue/assets/82224175/28cc00b0-ed85-4f70-b77d-8e2e79d863a3)

**Comment by Terrorforge** [comment]
I've had a lot of similar issues. Hammering buttons in all sorts of contexts seems to get various menu objects stuck. I've had the "Loading..." window get stuck, and just today I've had the game lock several times when I quit out of of the "Will you switch pokemon?" dialog and open the ESC/Start menu.

Seems to happen several times in a row and then not at all, so it might be something that only happens when the game is lagging a bit.

**Comment by j-diefenbach** [comment]
I've had the same if you just spam Z for 'add to party' and 'begin with these starters; prompt. It's mostly a case of 'just don't spam buttons together' but a backup check for these menus would be good. Since I think the yes/no prompt gets cleared on selection but clearly the starter options doesn't close on menu switch
