### ISSUE TITLE
[Bug] Phione does not learn Take Heart

### ISSUE THREAD

**Issue by Terrorforge** [pagefaultgames/pokerogue#1460]
According to both [Bulbapedia](https://bulbapedia.bulbagarden.net/wiki/Phione_(Pok%C3%A9mon)#Learnset) and [pokemondb](https://pokemondb.net/pokedex/phione), Phione is supposed to learn Take Heart at level 75, but it doesn't. Can't get it with memory shrooms, either.

I know the move is in the game and I haven't seen any other instances where level up learnsets deviate from the offical Gen 9 ones, so I assume this is just an error.

**Comment by chaosgrimmon** [comment]
Take Heart was added in Gen 8, as part of the PL:A changes. Phione and Manaphy currently have their Gen 4 learnsets, which were kept the same in canon through Gen 7.

In BDSP (Gen 8), the only difference from DP is that at level 1, both Phione and Manaphy learn Water Gun instead of Bubble and Water Sport.
Only in SV (Gen 9) (where neither even have a Pokedex entry,) do they learn Take Heart, at level 75 and 76, respectively. For Manaphy, this replaces Heart Swap, which is its signature move in every other mainline game.

[Relevant Code](https://github.com/pagefaultgames/pokerogue/blob/main/src/data/pokemon-level-moves.ts#L8450) if you wanted to demo making the changes yourself, but personally the current moveset as it is wasn't particularly a surprise.

**Comment by Terrorforge** [comment]
Thank you for pointing me in the right direction. I made the report last night and was thinking I might try and figure out how to do it today, but it looks like it's already taken care of. Next time I'll do it myself.

Is there a policy document or something where I can double-check things like "pokemon are supposed to use their Gen 9 learnsets"?
