### ISSUE TITLE
Pikachu forms showing as Mega Charizard X sprite

### ISSUE THREAD

**Issue by torranx** [pagefaultgames/pokerogue#1466]
- Clever pikachu
- Beautiful pikachu
![image](https://github.com/pagefaultgames/pokerogue/assets/68144167/54246c27-b72e-4d4d-8b61-74df5e6ff94a)

I'm not entirely certain if all forms are like this

**Comment by Madmadness65** [comment]
I'm pretty sure this is just an outdated image cache, because they appear fine for me: 
![image](https://github.com/pagefaultgames/pokerogue/assets/59298170/d5c0b5e6-8da1-4d90-a485-15bf2aad467b)
![image](https://github.com/pagefaultgames/pokerogue/assets/59298170/d7a520da-b16f-4792-b904-d53d5d0d94a1)

**Comment by torranx** [comment]
Tried on my local and issue isn't there too, also confirmed on discord:

<img width="742" alt="Screenshot 2024-05-28 at 10 14 45 AM" src="https://github.com/pagefaultgames/pokerogue/assets/68144167/c2158435-3e5c-4068-9155-e1f2529d5324">

Closing this issue.
