### ISSUE TITLE
[BUG] Minior core form is selectable as a starting form.

### ISSUE THREAD

**Issue by Smewkie** [pagefaultgames/pokerogue#1594]
When selecting Minior's forms in the starting select screen, you are able to cycle through them, for example:
Red Meteor
Orange Meteor
Green Meteor
Orange
Indigo

The colors there without the Meteor suffix start Minior in Core form, including a pop up at the start of battle to indicate that shield's down has activated, and when you get knocked down to 50% hp you get another pop up stating shield's down has activated again, when going back above 50% HP Minior still retains core form.

**Expected behavior**
In the mainline games, Minior is normally in Meteor form until it gets knocked down to 50% HP or below, and when it rises above 50% HP it changes back to Meteor form.

If this was a balance decision, my bad, sorry to waste y'alls time. :)

**Comment by Madmadness65** [comment]
This has now been fixed in 2863c5fb, thanks for the report.

**Comment by Smewkie** [comment]
you work fast! nice!

**Comment by Icehawk78** [comment]
Just a heads up - this was intentional, as the "forms caught" that are registered depend on the form it was in when you caught it.

So, if you had hatched a Red and Yellow Minior (which always is in Meteor Form from eggs) but caught a Blue Minior only after it form changed to Core Form, this change prevents you from choosing a Blue Minior as your starter. There were a number of discussions on Discord about how to handle this, but short of heavily revamping the Form logic to make a sort of "linked forms" logic, enabling both Core and Meteor forms to be selectable was an intentional choice (especially given that the Shields Down ability will convert back and forth regardless).

**Comment by Smewkie** [comment]
if shields down has been fixed to actually convert it back and forth, then that's fine! as it stood shields down was not changing the form at all, stats stayed the same above and below 50% health
