### ISSUE TITLE
[BUG] 145 rival boss pokemon gains extra HP barrier when reloading

### ISSUE THREAD

**Issue by RNGezeus** [pagefaultgames/pokerogue#1697]
I did a brief search for "Rival", "Barrier", "145" and couldn't find this mentioned

**Describe the bug**
If you reload the rival fight at 145 by any method then her starter gains an extra HP barrier

**To Reproduce**
Enter the 145 rival fight
Reset by any means, save & exit, refresh, disconnect
Check HP barriers

**Expected behavior**
I'd expect pokemon states to stay consistent to initial appearance.

**Screenshots / Videos**

https://github.com/pagefaultgames/pokerogue/assets/46976469/e888dbd9-7d29-41a5-be45-73e3a9030d63

**Device**
PC

**Additional context**
Is the game doing weird interactions with Rayquazas HP barriers since he has 3? I'll get back with an edit once I've also checked the 195 fight.

Edit: The 195 fight did not perform this behavior

Edit2: I don't know how I missed this the first time, but the Rayquaza also went up a barrier from 2 to 3
![Ray barrier](https://github.com/pagefaultgames/pokerogue/assets/46976469/c5b4ef66-e630-4f92-a09d-d9011863d558)

**Comment by Tempo-anon** [comment]
This is because the `pokemon.setBoss()` function looks like this 
```ts
setBoss(boss: boolean = true, bossSegments: integer = 0): void {
    if (boss) {
      this.bossSegments = bossSegments || this.scene.getEncounterBossSegments(this.scene.currentBattle.waveIndex, this.level, this.species, true);
      this.bossSegmentIndex = this.bossSegments - 1;
    } else {
      this.bossSegments = 0;
      this.bossSegmentIndex = 0;
    }
  }
  ```
When you refresh the bossSegments is treated as 0 so it tries to generate the boss segments based on `battle-scene.getEncounterBossSegments` the relevant bit of code is here:
```ts
    let ret: integer = 2;

    if (level >= 100) {
      ret++;
    }
    if (species) {
      if (species.baseTotal >= 670) {
        ret++;
      }
    }
    ret += Math.floor(waveIndex / 250);

    return ret;
```
So for cases like the 145 Rival, the Rayquaza is set to have 3 bars but if the player refreshes then it's recalculated and returns (2 + 1 + 1) = 4. This also applies to the rival's starter which in the video clip goes from 2->3. This is because it's manually set to 2 bars but on refresh and running through the getEncounterBossSegments code the calculation will be 2 + 1 = 3.

**Comment by Tempo-anon** [comment]
See https://discord.com/channels/1125469663833370665/1255267156036161596/1255267157265088693 for more discussion about this
