### ISSUE TITLE
[Feature] Add daily quests / login rewards

### ISSUE THREAD

**Issue by nico1207** [pagefaultgames/pokerogue#1758]
**Is your feature request related to a problem? Please describe.**

Not a problem

**Describe the Feature**

I think this game would benefit from adding some kind of daily/weekly quest system or also a daily login reward.
Example for quests: Beat 10 trainers, Train 5 Ghost-Pokemon to level 100, Beat the Top 4 once, etc.
Rewards could be egg vouchers, candy, maybe guaranteed legendary for 1 week login streak / hard weekly quest.

While these kind of features are controversial because of abuse by money-grabbing f2p games, they motivate and reward players for coming back to the game.

**Comment by Itsmax238** [comment]
I agree with the daily quests, they can add variety to gameplay. You may create an atypical lineup or play a gamemode you do not usually engage in for a daily quest.

However daily rewards are solely for the purposes of game retention and that is unnecessary on Pokerogue. The reason for game retention is so that users continue to be enticed to continue playing or tempted towards a purchase they would otherwise not make. However Pokerogue has no need for those things.

**Comment by Tempo-anon** [comment]
This just encourages addictive behavior. Right now the only reward for playing daily is access to different pokerus Pokemon and seeing the daily legendary gacha change.
