### ISSUE TITLE
[Feature] Explicit policy re: Pokerogue vs. official balance

### ISSUE THREAD

**Issue by Terrorforge** [pagefaultgames/pokerogue#1866]
**Is your feature request related to a problem? Please describe.**

Saw some discussion in #1836 (#1845 also relevant) about whether reverting the Dark Void nerf was warranted or not, the two sides largely coming down "yes, because it was only ever a problem in competitive" vs. "no, we should just use the current Gen 9 rules". I find myself bumbling into this problem myself when e.g. a pokemon is using an outdated moveset and I'm not sure if that's a bug or a feature.

**Describe the Feature**

Print a public policy document somewhere that explicitly states how these situations are supposed to be handled so the debate doesn't flarew up every time someone submits this type of PR.

Personally I'm not hugely concerned with what the policy actually is, so long as there is a policy. But in the spirit of open debate, I see three basic options for what it could be:

1. Stick as close as possible to official Gen 9 mechanics, with exceptions only when absolutely necessary for technical reasons or a game element simply makes no sense in the Pokerogue environment (e.g. Frisk change). AFAIK this is the current policy.
2. Allow reverting changes made in the official games when they make for a worse Pokerogue experience. Would presumably need to be judged on a case-by-case basis.
3. Allow any changes that improve the Pokerogue experience. Would presumably require further specifying which kind of changes are permissible, lest someone get the bright idea that Ember should be an 80-power spread move because they like Charmander.

**Additional context**

Personally I'm inclined towards a stance of strict Gen 9 parity just because it's the easiest to understand and invites the least argument. Also has the advantage that you can generally trust official resources to apply to pokerogue; if we allow arbitrary changes, documentation can easily become a problem.

**Comment by CodeTappert** [comment]
I agree with sticking as close as possible to Gen 9. Even if this isnt strictly "fun"

**Comment by Fontbane** [comment]
We do have resources to document changes. There’s [Ydrassiep’s dex] (https://ydarissep.github.io/PokeRogue-Pokedex/?table=speciesTable) with info for all the Pokémon, moves, abilities etc. which I believe pulls its info semi-automatically from this repository and specifies if a mon has been changed for the game. There’s also the [wiki](https://wiki.pokerogue.net/start) which I believe is listed on the escape menu. I wouldn’t consider documentation to be enough of an issue to withhold stuff like moveset additions.

**Comment by Mystery118** [comment]
Heavily against this, solely because every pokemon should be case by case. if a pokemon's current iteration works just fine, then great, use it, but in cases like darkrai, where its main gimmick becomes very hard to even use because of a heavy handed nerf by game freak, I think exceptions should be made. we should always prioritize what is best for each pokemon individually than following gamefreak's rules.

**Comment by ben-lear** [comment]
This is a different game, with different balance considerations than mainline Pokemon. Using Gen 9 as a starting point for everything is great, but there is absolutely no reason to strictly adhere to that design in cases where gameplay for Pokerogue could be enhanced (see: Pickup, stat boosts persisting between battles, etc.). Fun should be prioritized over a dogmatic need to adhere to arbitrary guidelines, especially since there is no PvP

**Comment by InnocentGameDev** [comment]
I'm arriving quite late to the thread, but I mostly agree with @CodeTappert in that a stricter version might be better on many fronts. One of them is accessibility to newer players. Do not ever forget you were new to this game at some point. The game already has many different things, and new players might get overwhelmed with it all.

In any case, of course some things from the mainline of games just do not work here, and those should be judged accordingly on a case-by-case basis. One such thing would be SuperLuck or Compound Eyes "out-of-battle" effect boosting enemy chances at having items, which would be detrimental. Rather than not implementing them at all, I think these should have their own unique adaptations to this game. In any case, these should not be the norm.

I think referring players to addons on wiki-checking, much as we may contribute to those, is a moot point and not something that should stand scrutiny. New players, especially the more casual ones, do not check wiki to learn these things.

Sometimes it's bad enough when Ivy surprises you with a random supereffective coverage move with 100BP, signature move of a legendary, on a random PKMN, because it took it from the egg-move pool. Dragon Ascent Gyarados being the last offender in one my runs. I KNOW Gyarados has one very niche flying type coverage move, and it's Bounce. I know it from playing PKMN for years, yet I get punished because I don't have memorised 4 super strong eggmoves for each PKMN evo line in this game. That's nuts.

Think about this, but now from a newcomer who might have made a plan to deal with Ivy at 195, and still got wrecked from something like this.

**Comment by Terrorforge** [comment]
To me the main problem with allowing arbitrary changes is mostly on the development end. We have enough trouble reaching consensus on things like egg moves without also calling every other aspect of every single pokemon into question. If every decision is made on a case-by-case basis, that's a _lot_ of work for the balance team and every PR risks becoming a bloodbath. No, we aren't beholden to the same silly schedule that Game Freak is, but we still need _some_ kind of structure so the whole game doesn't just turn into a mess of conflicting visions, and parity with official versions is by far the easiest way to do that.

But also yes, accessibility is an issue. Pokemon relies heavily on being able to intuit what each mon does, and making significant changes to that can really hurt your ability to understand wtf is going on.
