### ISSUE TITLE
Weird end-of-wave knockout damage interactions

### ISSUE THREAD

**Issue by Eridanus91** [pagefaultgames/pokerogue#222]
If a Pokemon is let's say, poisoned, it can get knocked out at the end of a wave. This creates some... interesting quirks.

If Pokemon in slot 1 gets knocked out like that in a double battle, the next wave softlocks until you restart the page, because Pokemon in slot 2 does not get properly removed and the game throws back the dead mon in, so the game becomes just enemy spamming their moves to no avail (hey, this sounds like that one glitch from Generation V games!).

![obraz0](https://github.com/pagefaultgames/pokerogue/assets/26799309/f1542d64-1f77-46d1-bec2-99fd501615ad)

If this happens during an area boss fight, it will cause certain graphics to not load, likely because the game forces you to switch out the dead mon in middle of everything.

![obraz](https://github.com/pagefaultgames/pokerogue/assets/26799309/121e8b17-7baa-43a1-bf2c-15ac367c43da)

**Comment by Lesys** [comment]
I got the exact same bug as OP. I don't know if it's because the double battle before (I did have a double battle before the bug occurring) but my Crocalor died from poison, then next fight I summoned Gyarados and the following picture explains what happened.

Fun fact that I was almost in the same level as OP with the same mon that died from poison :D

PS: I waited for the Ninjask to use all its PP and use Struggle, but it doesn't seem to have Struggle. Instead, its passive looped forever. I couldn't use any interaction, even ESC.

![image](https://github.com/pagefaultgames/pokerogue/assets/10529124/4805cc0b-dfdc-4bd9-8af7-1a9289ee2177)

PS 2: Thanks for the game ! Have been really fun the last 2 days I started it.

**Comment by knispeja** [comment]
Duplicated by:
- https://github.com/pagefaultgames/pokerogue/issues/253
- https://github.com/pagefaultgames/pokerogue/issues/894

**Comment by JoshuaKeegan3** [comment]
Fun fact. If the sprites are vanished from say desinty bond or toxic, Destroying a mimikyu disguise freezes the game

**Comment by flx-sta** [comment]
AAAANd this is actually a dupllicate of #64
