### ISSUE TITLE
[BUG] Stored Power TM learnset is incorrect

### ISSUE THREAD

**Issue by Tempo-anon** [pagefaultgames/pokerogue#2241]
**Describe the bug**
The list of pokemon that learn stored power through TM is incorrect

**To Reproduce**
Try learning in game

**Expected behavior**
Decide what should happen to Pokemon that lost it: https://bulbapedia.bulbagarden.net/wiki/Stored_Power_(move)

**Screenshots / Videos**
n/a

**Device**
n/a

**Additional context**
n/a

**Comment by 3ae3ae** [comment]
I've compared the wiki and tms.ts several times and didn't find any discrepancies.
Can you tell me more about what is incorrect?

**Comment by RNGezeus** [comment]
https://bulbapedia.bulbagarden.net/wiki/Stored_Power_(move)
The things I found: the file does contain Smoochum and Jynx despite not listed on bulbapedias overarching pacge, but this is likely a error on Bulbas side since they list as learning it on their individual pages.

Exeggcute, Exeggcutor (both forms), Deoxys and Manaphy couldn't be find in the file despite being on bulbapedia

Last of note is Meowstic which seems to be listed as only the female learning it, which was true in gen 8 but then males also got it next gen.
