### ISSUE TITLE
[BUG] HP not displaying correctly after evolution

### ISSUE THREAD

**Issue by PLMMJ-FH** [pagefaultgames/pokerogue#2352]
This really bizarre bug happened while I wasn't paying attention.
So I was fighting Surge, and my Toxtricity evolved. But when I had to send it out, until he hit me, its HP says 71/71, but its bar displays a bit of damage. It leveled up immediately after and everything was resolved (HP at proper max of 95)
![PokerogueWhyAreYouSoBroken](https://github.com/pagefaultgames/pokerogue/assets/159862724/130fb3e7-d7d3-4106-9cf2-7981e2947733)

**Comment by DayKev** [comment]
>  It leveled up immediately after and everything was resolved (HP at proper max of 95)

That's because you get auto-healed after a boss wave. If you had checked your Pokémon's HP from the party menu you would have seen it at 71/95 (or something similar).

---

For some reason when a Pokémon evolves there's a stale reference somewhere causing the Pokémon's HP to not be updated properly when it evolves.

After investigating for a bit, a possible reason is here in `src/field/pokemon.ts/PlayerPokemon:getPossibleEvolution()` (specifically line 3151 -> 3153): https://github.com/pagefaultgames/pokerogue/blob/fd7e547750a6109a955343a77d75c5994fceaf34/src/field/pokemon.ts#L3136-L3155

![image](https://github.com/pagefaultgames/pokerogue/assets/34855794/2a59019c-e547-426a-9e1a-55aed19cf134)

First the HP is calculated properly, but then it re-calculates using the original HP value and doesn't re-increase it to where it should be. I think the line(s) mentioned are causing the unnecessary first `calculateStats()` call and/or the stale reference which is messing things up.

The Pokémon I tested with in the image was Bulbasaur->Ivysaur Lv15->16.

**Comment by Snailman11** [comment]
Link to Discord's Bug Report (Health doesn't update after evolution)
https://discord.com/channels/1125469663833370665/1269015984258416743
