### ISSUE TITLE
[BUG] Sketch copies move from previous turn even if Smeargle moves second

### ISSUE THREAD

**Issue by dorox1** [pagefaultgames/pokerogue#2758]
**Describe the bug**

When Smeargle uses Sketch, it will copy the move used by the target on the previous turn, even if the target has used another move since then.

**To Reproduce**

1. Have Smeargle on your team and any non-Smeargle Pokemon as your lead.
2. Find an opposing Pokemon **with a higher speed than Smeargle**
3. Start the battle with the non-Smeargle Pokemon and immediately switch to Smeargle
4. Opponent uses **Move 1**
5. Select Sketch as your move for the turn
6. Opposing Pokemon uses **Move 2**
7. If **Move 1** and **Move 2** are different, Smeargle will Sketch the earlier **Move 1**

**Expected behavior**

Sketch should copy the most recently used move by the opposing Pokemon, even if it was used the same turn.

**Device**

Chrome Version 126.0.6478.116

**Additional context**

This problem may be difficult to replicate, as it relies on both facing a sufficiently fast opposing Pokemon and the AI's move selection being different between turns.

**Comment by schmidtc1** [comment]
Seems like SketchAttr currently pulls the target's move history and copies the first move in the history, instead of the last move. So, it's not related to switching actually, it will just always get the first move used in the opponent's history. I'll open a PR to fix

https://github.com/pagefaultgames/pokerogue/blob/13b23289d1203470271b56deeab35e9f07deeca1/src/data/move.ts#L5151-L5156

**Comment by Tempo-anon** [comment]
This has been fixed
