### ISSUE TITLE
[BUG] Beat Up deals no damage with the additional hits from Multi-Lens

### ISSUE THREAD

**Issue by innerthunder** [pagefaultgames/pokerogue#2767]
**Describe the bug**

When using Beat Up on a Pokemon with Multi-Lens, the additional hits created by Multi-Lens deal no damage.

Using Beat Up with Multi-Lens in a unit test shows that Beat Up deals "NaN" damage on the additional hits.

![image](https://github.com/pagefaultgames/pokerogue/assets/168692175/03270daa-a7c9-49d3-bdb7-cb379fc6db0b)

**To Reproduce**

Session Data: 
[sessionData1_innerthunder.zip](https://github.com/user-attachments/files/16081075/sessionData1_innerthunder.zip)

1. Load Session Data
2. Switch to Gremsicott (Greninja + Whimsicott fusion)
3. Use Beat Up
4. See how the move deals no damage after the first 6 hits.

**Expected behavior**

Beat Up should deal damage with every hit.

**Screenshots / Videos**

See above.

**Device**

Chrome

**Additional context**

N/A

**Comment by JackDixon019** [comment]
I think I see the issue. Commenting for future in case someone gets around to addressing this before I do:
allyIndex value is determined by taking [`user.turn.hitCount -  user.turn.hitsLeft`](https://github.com/pagefaultgames/pokerogue/blob/18dcef5b4a35bd41c5227f0d3d8cdd85b5e66f52/src/data/move.ts#L2740C23-L2740C70)

`user.turn.hitCount` is calculated with the [`getHitCount` func (case MultiHitType.BEAT_UP)](https://github.com/pagefaultgames/pokerogue/blob/18dcef5b4a35bd41c5227f0d3d8cdd85b5e66f52/src/data/move.ts#L1665) 

When using multi-lens, [this results in multiplying the `hitCount` and also therefore the hitsLeft ](https://github.com/pagefaultgames/pokerogue/blob/18dcef5b4a35bd41c5227f0d3d8cdd85b5e66f52/src/modifier/modifier.ts#L1855C5-L1855C74) (i think, not 100% that is what args[1] is referring to, but it's the only thing that makes sense). When hitCount - hitsLeft > number of pokemon, you get issues.

e.g. with 6 pokemon and 1 multi-lens:
```
(hitCount, hitsLeft, allyIndex)
(12, 12, 0)
(12, 11, 1)
(12, 10, 2)
...
(12, 6, 6) -> will cause errors since allyIndex[6] does not exist
```

fix: allyIndex should instead be `Math.floor(user.turn.hitCount / (1+ $multilensCount) -  Math.floor(user.turn.hitsLeft / (1+ $multilensCount)))`
I have to look further into how to get the multilensCount though, so if someone does know how to get that and can fix it before I get around to it, feel free to do so. This also isn't exactly a perfect fix, since I think it would double-count each member of the party, so the first round of beat up would be from the first 3 mons and the second round would be from the second 3 mons.

**Comment by innerthunder** [comment]
Ended up going by eligible party count (i.e. the number of Pokemon in the user's party that do not have a non-volatile status condition) instead with the above PR:
```ts
allyIndex = (user.turnData.hitCount - user.turnData.hitsLeft) % eligiblePartyCount
```
So with one Multi-Lens this would cycle through the eligible party members twice, for example
