### ISSUE TITLE
[BUG] Starter Cosplay Pikachu are missing thier signature move 

### ISSUE THREAD

**Issue by GrohJann** [pagefaultgames/pokerogue#2783]
**Describe the bug**
When starting a new game, the signature moves for the Cosplay Pikachu variants (eg. Icicle Crash for Beauty Cosplay Pikachu or Flying Press for Tough Cosplay Pikachu) are missing. I currently only have verified this for the Tough and Beauty Cosplay Pikachu variants in the starting menu, as I haven't come by the others so far. 

**To Reproduce**
1. Start a new game
2. Choose Cosplay Pikachu (at least Tough or Beauty)
3. notice that their signature moves are missing

**Expected behavior**
Cosplay Pikachu should have their signature move from the start of the game

**Screenshots / Videos**
![image](https://github.com/pagefaultgames/pokerogue/assets/43465062/8b89e5be-f54a-4702-bc75-d3ce0fd68dcc)
![image](https://github.com/pagefaultgames/pokerogue/assets/43465062/439b5312-b65d-4895-a234-b924de66c963)

**Device**

Linux Firefox
Linux [App](https://github.com/Admiral-Billy/Pokerogue-App) which seems to be chromium based

**Comment by Ganpan14O** [comment]
Having the same issue but I know I started with icicle crash before, maybe an issue with not being able to get it back if you switch it out?

**Comment by GrohJann** [comment]
I too have started out with a signature move (Flying Press) before, but I haven't switched out any attacks, so I don't believe that's the cause for the issue.

**Comment by 22patriciaaz22** [comment]
![image_2024-07-06_152833611](https://github.com/pagefaultgames/pokerogue/assets/50278452/51fabc94-dfd2-42e2-aea4-5d21de5861ce)
The moves are still in the move sets for the Pokémon, if you play a run with them you can use a memory mushroom to regain the move, apparently. Have this bug very noticeably removing Hydro Pump from my Rotom as a starter currently. :/  Hope this gets fixed soon I had gotten very cozy using Hydro Pump Rotom for luck up.

**Comment by 22patriciaaz22** [comment]
As additional information to my screenshot above, it does appear to move the starting move order as if there was meant to be the signature move there when in the starter menu. It seems like perhaps the issue is when you switch the forms in the starting menu the signature move isn't added to the form itself. It is clearly still in the total move pool for the special version, but since you wouldn't be able to add the signature move yourself anyway I think it must be that whatever coding queue puts the signature move into the move set is currently broken.

**Comment by Snailman11** [comment]
Link to Discord https://discord.com/channels/1125469663833370665/1258164414247600233
