### ISSUE TITLE
[Bug] Can't switch because of Arena Trap doesn't show on switch screen

### ISSUE THREAD

**Issue by Anusien** [pagefaultgames/pokerogue#3217]
### Describe the bug

I was in a trainer battle, and I tried to switch my Pokemone. I was on the switch screen and I kept selecting the monster and hitting Send Out. Nothing happened. When I stopped and continued with the fight, I got all the "Can't switch because of Arena Trap" messages in the battle box. So the logic worked correctly, but the message didn't show at the right time.

### Expected behavior

The "can't switch out" message should appear on the Pokemon screen, not the battle screen.

### What OS did you observe the bug on?

Mac/OSX

### Which browser do you use?

Chrome

**Comment by Snailman11** [comment]
Discord Link (Shadow Tag Pops Up Inappropriately) https://discord.com/channels/1125469663833370665/1267175681398145054
-Happens after trying to catch a trainer's pokemon

**Comment by chansyu** [comment]
- The same interaction happens if you try to run away from the enemy pokemon as well. 
- I believe the same cause of this issue also caused #2524 in the past.
 
I observed that the when the player tries to attempt the disallowed action (run away or switch pokemon), a message phase is appended to the phaseQueuePrepend without commencing these message phases.
Whenever the player does a legal action afterwards, then the appended messages are shown.

Probably need to just show these messages immediately instead of going to phaseQueuePrepend.

**Comment by Anusien** [comment]
When you level up a Pokemon and it learns a move, it now shows you the dialog to learn the move and forget an old one in the next fight.

**Comment by innerthunder** [comment]
fixed by https://github.com/pagefaultgames/pokerogue/pull/3271
