### ISSUE TITLE
[Bug] Disguise reverts to original form if damaged on switch-in

### ISSUE THREAD

**Issue by fishsicles** [pagefaultgames/pokerogue#3463]
### Describe the bug

A damaged Mimikyu switched in to my Stealth Rock, causing it to revert to its original form and reset Disguise.

### Expected behavior

Mimikyu's Disguise ability should only trigger once per battle.

### What OS did you observe the bug on?

PC/Windows

### Which browser do you use?

Firefox

### Additional context

Local offline instance, but latest version.

**Comment by Snailman11** [comment]
This occurs not just when switching in on hazard, but everytime Mimikyu switches in. 
Discord Bug report with current Disguise Problems: https://discord.com/channels/1125469663833370665/1267306283275386912 (Mimikyu Disguise Ability resets aftet switching out.)

This issue should be fixed with Daykev's PR 
https://github.com/pagefaultgames/pokerogue/commit/c64e80d57e42454238b737a00f4955b74356cece (Refactor Disguise to work like Ice Face)
