### ISSUE TITLE
Oricorio Forms

### ISSUE THREAD

**Issue by S0m30n3Unk0wn** [pagefaultgames/pokerogue#3721]
### Describe the bug

On the new game menu when I go down to Oricorio there's no 'f' command (bottom left section of screen) to change form and when I press 'f' Oricorio will still not change forms

### Expected behavior

Change oricorio form before start of game to use

### What OS did you observe the bug on?

PC/Windows

### Which browser do you use?

Edge

**Comment by Snailman11** [comment]
Have you caught more than one oricorio form?

**Comment by LilyAlternis** [comment]
![Oriocorio](https://github.com/user-attachments/assets/94b9c755-5274-400e-85ba-ec993162f401)
I can confirm atleast its there in Chrome and in game, so its either a user/browser only bug until now since I havent seen any report similar to this in the discord. 
So please supply with more information so we can better help ^_^
