### ISSUE TITLE
Poke balls can still be used on wild pokemon that have vanished using phantom force

### ISSUE THREAD

**Issue by Scepty-SSB** [pagefaultgames/pokerogue#411]
I'd assume that something similar occurs with dig, dive, fly, etc. but I haven't checked

**Comment by bennybroseph** [comment]
While this is not how it works in the mainline games, I assume this will be kept because it benefits the user. Would be pretty annoying to have to wait for a Pokemon spamming these moves every other turn to throw a ball.

Honestly I already find it rough to need to kill a Pokemon in double battles, but I assume that is kept for balance reasons as being able to catch twice as many Pokemon is pretty busted in endless.
