### ISSUE TITLE
 Mystery Encounters beta bugs/breakfix 2

### ISSUE THREAD

**Issue by flx-sta** [pagefaultgames/pokerogue#4300]
Please add any bugs, session saves, screenshots, logs, etc. here in comments so they can be tracked under this issue

This is a follow up issue for #4240

**Comment by VaylenObscuras** [comment]
ME with the choice of 3 trainer battles. Went for "mightiest" and was surprised to see that my delphox retained its Quiver Dance boosts. I was under impression that boosts should be reset when an encounter happens.

**Comment by PigeonBar** [comment]
(Originally from https://github.com/pagefaultgames/pokerogue/issues/4240#issuecomment-2354448815)

Sometimes, if you save and quit a session which had encountered ME's, and then start a new run, the game can incorrectly apply and save `mysteryEncounterSaveData.encounteredEvents` from the old session to the new session. This can cause the game to refuse to spawn ME's due to the "do not spawn an ME within 3 waves of the last one" check.

I was able to continue reproducing this bug after applying the changes from https://github.com/pagefaultgames/rogueserver/pull/52. In fact, this bug is probably more common now, and it appears to no longer fix itself after a reload.

![20240917 Encountered Events](https://github.com/user-attachments/assets/b678ebb0-2541-4c19-9440-d699ca992b11)

**Comment by PigeonBar** [comment]
In Department Store Sale, there is a weird edge case that happens when you have a party of Pokemon that cannot learn any TMs, then you choose to go to the TM counter:

https://github.com/user-attachments/assets/edf51bce-6a6d-4068-8dbd-cfce99e7a9bb

**Comment by PigeonBar** [comment]
The game allows you to open the menu while scrolling the ending dialogue text after an ME (this is easier to trigger at lower game speeds), which then allows you to use the egg gacha exploit to save any meta-progression that the ME awards. Here is an example of saving an epic egg from A Trainer's Test:

https://github.com/user-attachments/assets/3022aa9d-44a3-4929-a175-eb6c33579aac

**Comment by PigeonBar** [comment]
If the Mysterious Chest's unlucky option KO's your only healthy Pokemon, and you click "Yes" to retry the battle, it now crashes the game:

https://github.com/user-attachments/assets/8f583055-c329-4089-91a1-d3717e0bc130

**Comment by Snailman11** [comment]
Health Ui Disappears After "Weird Dream" ME

> (beta) the “mysterious women” mystery event removes Pokémon health bars
https://discord.com/channels/1125469663833370665/1285854633247637514

**Comment by PigeonBar** [comment]
> If the Mysterious Chest's unlucky option KO's your only healthy Pokemon, and you click "Yes" to retry the battle, it now crashes the game:
> 
>  20240917.Mysterious.Chest.Crash.mp4

Update: I think the crash was unrelated to Mysterious Chest, and the game just crashes whenever you click "Yes" to retrying a battle:

https://github.com/user-attachments/assets/157b307f-4125-4521-8b62-de9ec46ee5d5

**Comment by PigeonBar** [comment]
(In Safari Zone, all RNG rolls for bait, catch attempts, and wild Pokemon flee attempts share the same RNG seed and can influence each other across all 3 wild encounters. We may want to revisit this after we are done dealing with higher-priority issues.)

**Comment by PigeonBar** [comment]
I think Fight or Flight's randomly boosted stat now has a different off-by-one error that prevents the wild Pokemon's speed from getting boosted. It should be `randSeedInt(5, 1)`.

![20240918 Stat Boost RNG](https://github.com/user-attachments/assets/d5330880-b09a-4b33-b19f-9ae4fbe96cbb)

**Comment by PigeonBar** [comment]
If shininess only gets rerolled when the Pokemon isn't shiny, then we may need to watch out for situations where a wild Pokemon being shiny can cause one fewer RNG call to occur, which can further influence RNG outcomes.

![20240918 Reroll Shiny RNG](https://github.com/user-attachments/assets/14c5b3e6-3608-4cc3-a3d5-d4ce01915a2b)

**Comment by PigeonBar** [comment]
I think the attempted fix for wild Pokemon's levels changing upon reload is now causing the wild Pokemon to become completely different upon reload, since the attempted fix calls RNG to determine the Pokemon's level after a reload:

https://github.com/user-attachments/assets/ddb266c5-c6cb-4d26-8d2d-627c5b1357db

**Comment by PigeonBar** [comment]
Phione can spawn in the Safari Zone:

![20240918 Phione Safari Zone](https://github.com/user-attachments/assets/f69cd54b-163c-427a-88b0-91707f4e8e64)

My testing save file:

[20240918 Phione Safari Zone.zip](https://github.com/user-attachments/files/17050713/20240918.Phione.Safari.Zone.zip)

**Comment by PigeonBar** [comment]
(According to https://bulbapedia.bulbagarden.net/wiki/Catch_rate#Great_Marsh_and_Johto_Safari_Zone, the Safari Zone catch rate formula is designed for 4 shake checks, but PokeRogue only does 3 shake checks. We may want to revisit this after dealing with higher-priority issues first.)

**Comment by Snailman11** [comment]
"Department Store" Can appear in the Swamp, which is not a 'Civilization' Biome
> [BETA] Department Store Sale Mystery Encounter Triggers in Swamp

https://discord.com/channels/1125469663833370665/1286329606349000780

**Comment by PigeonBar** [comment]
Fiery Fallout can attempt to burn a Pokemon that is already burned, which makes it appear to not burn any new Pokemon. Is this intended?

https://github.com/user-attachments/assets/5415b1a3-f8c7-45e4-87a2-dd304a1abcce

**Comment by PigeonBar** [comment]
If you splice two Pokemon each holding a Shuckle Juice, you can get a Pokemon holding multiple Shuckle Juices. Is this intended?

![20240919 Splice Shuckle Juice](https://github.com/user-attachments/assets/83ca4bc7-0b7c-4b41-9bde-8bb6d9b9e0c2)

**Comment by PigeonBar** [comment]
Shuckle Juice doesn't seem to get applied correctly after a reload. In this recording, notice how Lapras loses its Shuckle Juice item in the top-left corner, and also notice how its max HP increases from 3760 to 3920.

https://github.com/user-attachments/assets/ffb0cc8c-6524-44fc-a66f-5813d45774f2

**Comment by flx-sta** [comment]
The `delibirdy` encounter varies depending on the language (English is the only one that is punished).


This`modifier.type.name.includes("Berry")` is at fault: https://github.com/pagefaultgames/pokerogue/blob/7490699bef72672874ca009addf363b27ebad8a3/src/data/mystery-encounters/encounters/delibirdy-encounter.ts#L197-L200


Instead it should be:

```ts
          const modifier: BerryModifier | HealingBoosterModifier = encounter.misc.chosenModifier;

          // Give the player a Candy Jar if they gave a Berry, and a Healing Charm for Reviver Seed
          if (modifier instanceof BerryModifier) {
```

**Comment by pom-eranian** [comment]
mystery event assets need a naming convention

**Comment by flx-sta** [comment]
> Reddit:
> [kmnjkhmulolfml](https://www.reddit.com/user/kmnjkhmulolfml/)
> I found a small glitch where spin winning the master ball tier item (multi lens) from the whack-o-matic, every pokemon in my party got replaced with the pokemon I used to play the minigame with. In my case, all my party members were replaced with a level 15 chi-yu. The slight benefit of this glitch is that it also duplicated the multi lens I had one, now giving me 3 copies, one for each party member turned into chi-yu.

https://www.reddit.com/r/pokerogue/comments/1fkasry/comment/lnukgvr/?utm_source=share&utm_medium=mweb3x&utm_name=mweb3xcss&utm_term=1&utm_content=share_button

**Comment by Blitz425** [comment]
![image](https://github.com/user-attachments/assets/5cafde69-f241-4443-9421-c7ee3f563aa5)
![image](https://github.com/user-attachments/assets/9ea07778-b651-46c7-b79a-564013c4f443)

Wonder Trade states I was getting a Mega Kangaskhan, luckily it wasn't actually a mega but that is very bad haha

**Comment by PigeonBar** [comment]
[An Offer You Can't Refuse] In challenge modes, this ME is allowed to spawn when you have only 1 challenge-eligible Pokemon (confirmed using an extra `console.log()`, this ME has ID 14), and it can offer to buy your only challenge-eligible Pokemon, which would lead to a game over.

https://github.com/user-attachments/assets/b14d68cd-59ab-41fc-99a6-d94ed7e0dfc0

**Comment by flx-sta** [comment]
The `berries-abount` tests fail sometimes because there is only 1 Pokemon in the party and it might hit max-stack of a berry.
Thus the expected amount of berries falls lower than the original defined.

----

An easy solution for now would be to just increase the party-size in the test

A long-term solution might be to re-roll a berry that can't be replaced. This has to take into account a max-loop as the whole party could be capped with a berry and we don't want it to be stuck in an endless loop.

**Comment by star-krieg** [comment]
Retrying Uncommon Breed ME causes a crash

![image](https://github.com/user-attachments/assets/04155de9-b361-4155-9dc9-c1f31216fdf8)

**Comment by PigeonBar** [comment]
Is it intended for Weird Dream to erase a Pokemon's shininess and luck value? I guess the answer is "Yes" because of the mechanic where all shiny transformed Pokemon get unlocked as starters. However, this could mess up players who brought shiny starters for higher luck.

https://github.com/user-attachments/assets/9f555a09-6e45-4f07-9b4d-4483a8e865d5

**Comment by PigeonBar** [comment]
Wild encounters can still turn into ME's upon reload, this time due to an RNG bug:

https://github.com/user-attachments/assets/393e9234-7267-4d57-8999-a5ba891bc470

My testing session file:

[20240920 ME Reload.zip](https://github.com/user-attachments/files/17075794/20240920.ME.Reload.zip)

I think I've traced it down to:

- Before reload:
  - The game calls RNG once to decide whether or not there will be a trainer battle.
  - Then, the game calls RNG to decide whether or not there will be an ME.
- After reload:
  - The session save file says "there is no trainer", so the game does NOT call RNG to decide whether or not there will be a trainer battle.
  - Then, in a different RNG state, the game calls RNG to decide whether or not there will be an ME.

A potential solution could be to find a way for the session save file to store "there is no ME", similarly to how it can store "there is no trainer".

**Comment by flx-sta** [comment]
@PigeonBar please don't link `.zip` files.
They are not considered save! Instead you can simply upload the files as `.txt` (they are nothing else anyway)

**Comment by Snailman11** [comment]
In "Fight or Flight", if you attempt to steal an item, then switch the active pokemon when prompted, the Player Sprite is stuck on screen.

> Player behind Pokemon (beta)

https://discord.com/channels/1125469663833370665/1286739532427034654

**Comment by PigeonBar** [comment]
[Delibirdy] If you give Gimmighoul's evolution tracker item to the Delibirds, it causes the game to crash:

https://github.com/user-attachments/assets/e36c0c2f-e02e-4e66-aebb-94bcfd57a3b3

**Comment by PigeonBar** [comment]
[Delibirdy] If you give a Macho Brace item to the Delibirds, then:
1. If the Macho Brace is at a stack of 1, you completely lose the item and can no longer train to increase its stack count.
2. If the Macho Brace is at a stack of at least 2, you only lose 1 "training progress" and can continue using the Macho Brace.

**Comment by PigeonBar** [comment]
[Delibirdy] Form change items are, in fact, also `PokemonHeldItemModifier`s, and can be gifted to the Delibirds without reverting the Pokemon's form change:

https://github.com/user-attachments/assets/d3e51fa0-252b-4e67-8ca3-34a23523c8d4

**Comment by PigeonBar** [comment]
Weird Dream also erases Pokerus:

https://github.com/user-attachments/assets/b35f20fe-3565-4d00-bfc4-3a8f3c47e7c9

**Comment by PigeonBar** [comment]
(Originally from https://discord.com/channels/1125469663833370665/1284608904906407976/1284608904906407976)

The bug where reloading in Absolute Avarice deletes all berries is still active. Notice how Greedent spawns with no berries after the reload, since there were no berries for it to steal.

https://github.com/user-attachments/assets/16f36bf0-5e4f-48da-a2f7-0630f355275e

**Comment by PigeonBar** [comment]
[Absolute Avarice] If a Pokemon is already holding a Reviver Seed and is about to get rewarded with another Reviver Seed, the game announces "Stack for Reviver Seed is full" before announcing "Your party gains Reviver Seeds", which can look a bit weird:

https://github.com/user-attachments/assets/05fb8c74-b47b-47a3-9591-b9e661ce24d2

**Comment by PigeonBar** [comment]
For ME's where the opponent Pokemon gets displayed before battling the Pokemon, should the Pokemon be shiny-locked?

https://github.com/user-attachments/assets/45122c07-b701-4ee6-9ae5-dba354b7b082

**Comment by PigeonBar** [comment]
[Berries Abound] A minor RNG bug: Only the first berry gets generated with a seed offset, which means the rest of the berries can change based on the RNG calls made during the battle before earning the berries:

![20240921 Berries Abound RNG](https://github.com/user-attachments/assets/6c1c13c4-3834-43e5-b01c-0ee32385d89f)

**Comment by PigeonBar** [comment]
Now that #4369 is in progress, should we make a new “ME bugs thread 3”?

**Comment by ben-lear** [comment]
> Now that #4369 is in progress, should we make a new “ME bugs thread 3”?

Need to copy over some issues that weren’t fixed yet but yeah

**Comment by ben-lear** [comment]
Closing this issue, all bugs that weren’t fixed yet have been marked in the follow up issue:

https://github.com/pagefaultgames/pokerogue/issues/4372
