### ISSUE TITLE
[Bug] 'New Game' stays on a black screen!

### ISSUE THREAD

**Issue by Epic-Mawer** [pagefaultgames/pokerogue#4434]
### Describe the bug

Whenever I try to play a new game, the screen stays and is stuck on a black screen. The music still plays, but I can't even press anything to exit! The only way I know how to fix this is to create a new account, but that's annoying...

Does anyone know how to fix this?

### Expected behavior

I wanted to access the 'New Game' menu.

### Screenshots / Videos

![Screenshot 2024-09-25 211210](https://github.com/user-attachments/assets/ada71f8d-d43a-41d6-8f3e-7b6acac925f1)

### What OS did you observe the bug on?

PC/Windows

### Which browser do you use?

Edge, Opera

**Comment by flx-sta** [comment]
@Epic-Mawer can you please open your JS console and show us the content?
(screenshot or print, either works)

**Comment by MokaStitcher** [comment]
Already fixed with #4209 
Can you confirm that this is indeed the same issue by following the instructions here, then close this issue if it is 

1. Open the devtools with F12
2. Go to the "Storage" tab (you may need to click the ">>" to see it)
3. Go to "Local Storage" > "pokerogue.net"
4. In the list of items that appear, find one that is called `starterPrefs_YourUsername``
5. Right click on it, and chose delete
6. Refresh the page and you should be good to go

**Comment by MokaStitcher** [comment]
No response, 99% sure it was the same issue that the PR I linked above fixed. Closing
