### ISSUE TITLE
Opponent pokemon sprite disappears after using Roar

### ISSUE THREAD

**Issue by PaulBeslin** [pagefaultgames/pokerogue#481]
When an opponent pokemon (Trainer or wild) uses Roar, its sprite disappears. The pokemon is still here and behaves properly, except for the sprite.
Other moves such as whirlwind do not seem to be affected.
Using Roar as the player works as intended.

To reproduce, override the opponent used move to be Roar.

![image](https://github.com/pagefaultgames/pokerogue/assets/71925152/ef3c55a5-043e-4a46-a3c9-49a444a17147)

**Comment by happinyz** [comment]
PR for the fix: https://github.com/pagefaultgames/pokerogue/pull/625

**Comment by happinyz** [comment]
> PR for the fix: #625

I suspect this is something wrong with the animation file, rather than any move application/attribute logic. When changing Roar's attributes to the exact same ones as Whirlwind's, this bug still happens. However, when I switch Roar's animation to use Whirlwind's, this bug does not appear.

I tried playing around with the animation file a bit but I'm not super familiar with how the animation framework works. I've closed my PR for now. I welcome anyone who's more familiar with the animation system to tackle this bug.

**Comment by pom-eranian** [comment]
Copy pasted from discord since the issue was brought up there. 

I already tried changing or removing the anim file's parameters one by one and it still happened.
The behavior I saw every single time is that no matter who used the move, player or opponent, the opponent disappeared after the anim ends and before the player team UI shows up.
Then I tried extending and shortening the amount of frames, and every time the opponent would disappear after the anim was done.

_However having another move do the same thing is interesting.  Does anyone know if baneful bunker already did this or is it a new bug?_ It's new.

The only part that can be fixed through the anim file is the little blip at the end like this: https://github.com/pagefaultgames/pokerogue/pull/1660#issuecomment-2154936069

**Comment by Snailman11** [comment]
Link to Discord (Bug report deleted so chat link) https://discord.com/channels/1125469663833370665/1125894949020381285/1267314975953780808

**Comment by flx-sta** [comment]
After some debugging I noticed that only `Roar` and `Dragon Tail` seem to do a false-swap of `user` and `target` during the animation. 
I was fighting with `Charmander` vs a wild `Surfskit`
I'm going to dump some debug messages in here to show what I mean

------

### Roar

```
anim:  PRAS- Roar 
    User Charmander  | this.user: Surskit 
    Target Surskit  | this.target: Charmander
```

------

### Dragon Tail

```
anim:  PRAS- Dragon Tail 
	User Charmander  | this.user: Surfskit 
	Target Surfskit  | this.target: Charmander 
```

----
----

### Whirlwind

```
anim:  PRAS- Twister 
    User Surskit  | this.user: Surskit 
    Target Charmander  | this.target: Charmander
```

----

### Scratch

```
anim:  PRAS- Slash 
    User Charmander  | this.user: Charmander 
    Target Surskit  | this.target: Surskit
```

**Comment by flx-sta** [comment]
And I found the code that is causing this.
Now the question is: why was it coded that way? is there a reason?

```ts
  isOppAnim(): boolean {
    return !this.user?.isPlayer() && Array.isArray(moveAnims.get(this.move));
  }
  ```
  
  So because `roar.json` and `dragon_tail.json` are an array instad of an object (start with `[` and end with `]` in the file) they are not considered enemy animations.
  I have not a single clue why that condition exists but I'd have to investigate why it was put there in the first place

**Comment by flx-sta** [comment]
### Using Roar with ~~`Array.isArray()`~~ removed

```
anim:  PRAS- Roar 
    User Charmander  | this.user: Whismur 
    Target Whismur  | this.target: Charmander 
    Is Opponen Animation: true 
```

https://github.com/user-attachments/assets/069121f7-3b1c-4910-8e13-cb102824dbee
