### ISSUE TITLE
Lingering Effects

### ISSUE THREAD

**Issue by Rellekeel** [pagefaultgames/pokerogue#59]
After around a thousand floors total I have noticed that some effects seem to linger match to match that shouldn't. If you get sand-attacked by your opp, then the accuracy drop seems to stay until a switch out. Fog accuracy drops continue map to map regardless if the weather is sunny/clear/rain. Floor hazards like spikes, toxic spikes, etc continue floor to floor. 
If is intentional I apologize, but the accuracy drops seemingly moving with you after your first fog encounter is a miserable experience.

**Comment by Flashfyre** [comment]
Hazards and stat changes continuing between floors is intentional. Fog effects happening when there is no fog is not though. Are you sure this part wasn't just bad RNG? The logic doesn't really allow for this kind of thing, as the effects of fog are not persisted anywhere and it checks the weather each time a move is used.

**Comment by thaumasiotes** [comment]
I can report that entry hazards (for me, toxic spikes) persist between battles even after you use rapid spin, which should clear them. Are they really intended to be permanent? Why?
