### ISSUE TITLE
Mismagius shiny sprite

### ISSUE THREAD

**Issue by Diamnd08** [pagefaultgames/pokerogue#677]
I reciently got a shiny misdreavous that was purple and not green, and when it evolved mismagius’s sprite was like a blue but the sprite in the party menu is yellow?
This is what it shows:
Uploading 73695035465__62EBB2D8-B86A-40D0-8AF8-1CADA65DECBE.MOV…

**Comment by j-diefenbach** [comment]
there are alternate shinies im thinking you had one of those, however there aren't alternate shiny pngs for mismagius the evolution after checking the files so that might explain why it appears different in the party menu and ingame. One is using the png and the other is using the palette to modify the regular sprite. These are the alternate shinies for misdreavus im guessing the first one is the one you saw?
<img width="470" alt="image" src="https://github.com/pagefaultgames/pokerogue/assets/105332964/774274ba-6446-4b60-a82d-935d02ef66a8">
<img width="470" alt="image" src="https://github.com/pagefaultgames/pokerogue/assets/105332964/efcb8245-d74e-404c-b002-5870ce0cf29b">

**Comment by Diamnd08** [comment]
Yea

**Comment by Diamnd08** [comment]
I just saw that for misdreavous the ends of its hair is gold now blue? Same for mismagius
