### ISSUE TITLE
2 Turn moves bug

### ISSUE THREAD

**Issue by hightowernl** [pagefaultgames/pokerogue#707]
When paralyzed and using a 2 turn move like Electro Shot there is a bug that prevents to change your move if you get fully paralyzed on the 2nd turn. 

The way it works now is:
-Charge move
-get full para
-game automatically charges again (1st turn)
-get full para
-game automatically charges again (1st turn) etc until you stop getting fully paralyzed.

Had this 4x in a row with my Archaludon. I imagine it's the same for moves like Dig, Sky Attack, Dive, Fly and more.

**Comment by hightowernl** [comment]
And I just found out it's also like this after you hit yourself in confusion. Safe to say it's also with flinch

**Comment by hightowernl** [comment]
Aaand if the opponent uses Dig before the player wants to use Electro Shot, it won't work, not even charge the move.

**Comment by Matakor** [comment]
adding to this, if your poke is paralyzed, and uses dig, there seems to be a chance that it can be unable to move after digging, which then causes it to re-use dig again and again until it does go through twice. This effectively makes you semi-invincible until the dig is complete, which when I first hit this bug, lasted about 8 turns.

I don't remember how the orig game works with this, but I think it was that if the 'charge' worked, the 'follow-up attack' also worked. That or it just interrupted it and made you start back over from pre-charge state. It's been a long time since I played main-line poke

**Comment by bennybroseph** [comment]
Fixed here https://github.com/pagefaultgames/pokerogue/pull/741

**Comment by hightowernl** [comment]
> Fixed here #741

Nice!

Don't know if I should make another thread, but I just noticed Phantom Force failed on the 1st turn because my opponent also used Phantom Force and did it before me.

**Comment by hightowernl** [comment]
And Sketch failed because Phantom Force failed to be used on my Delcatty since it's a Normal type.
