### ISSUE TITLE
Double-battle intimidate appears to trigger twice

### ISSUE THREAD

**Issue by umbra3275** [pagefaultgames/pokerogue#82]
In a double battle, if the intimidate pokemon is the second one (on the right, second party slot), then it will trigger intimidate and lower both opposing mon's attacks, then it will trigger intimidate again, and do the same.

**Comment by Flashfyre** [comment]
Does this happen only on loading a save or always?

**Comment by umbra3275** [comment]
I haven't tried it when loading a save, I noticed it in normal gameplay

**Comment by adrienntindall** [comment]
I've seen this bug a lot playing with staravia, I think it happens when you switch the left Pokemon into anything then switch(?) the right pokemon into something with intimidate, it triggers the right mon's intimidate twice. Very useful to abuse but also should be fixed (not by me tho you web devs scare me)
