### ISSUE TITLE
What happened to hybrid saving?

### ISSUE THREAD

**Issue by karl-police** [pagefaultgames/pokerogue#877]
https://github.com/pagefaultgames/pokerogue/commit/794363348199fd0df31dc0ba394b6c88a4da561c

**Comment by Flashfyre** [comment]
It caused saves to be unintentionally shared across accounts, it frequently locked you entirely out of devices due to not always loading system data on the server, and introduced new exploits to duplicate vouchers and other one-time rewards. Needless to say, it was not worth the trouble of keeping this changeset in until these issues were fixed. It will be reintroduced when all the problems are addressed.
